server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/IoT?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #Redis 配置
  ##默认密码为空
  redis:
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000
    # 连接超时时间（毫秒）
    timeout: 5000
    #默认是索引为0的数据库
    database: 0
logging:
  level:
    root: info
  # 输出日志到文件 自动根据max-size 分割
  file:
    max-size: 10MB
    max-history: 7
    name: e:\Users\60586\Desktop\temp\proper_Iot\proper_Iot.log
---
spring:
  profiles: produce
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.111:33306/liliao_puri?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: Proper123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #Redis 配置
  ##默认密码为空
  redis:
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000
    # 连接超时时间（毫秒）
    timeout: 5000
    #默认是索引为0的数据库
    database: 0
logging:
  level:
    root: info
  # 输出日志到文件 自动根据max-size 分割
  file:
    max-size: 10MB
    max-history: 7
    name: proper_Iot.log